"""The Huffman code HPACK uses for header names and values.

RFC 7541 section 5.2 and appendix B. The code is fixed: it was built once from a
sample of real header traffic and shipped inside the specification, so there is
nothing to negotiate and nothing to learn at runtime. The tables live in
`_huffman_data.mojo` and are generated by `tools/gen_huffman.py`.

Encoding is a loop over a bit accumulator. Decoding is a state machine over four
bit nibbles rather than a walk down a code tree, so a byte costs two table
lookups instead of up to thirty branches.

Decoding is where the bounds are, because decoding is the half an attacker
controls. Three things are refused outright:

The EOS symbol appearing in the middle of a string. RFC 7541 section 5.2 says an
encoding containing it must be treated as a decoding error, and the generated
table marks every transition that reaches it, so this costs nothing to check.

Padding that is anything other than a proper ending. The padding must be the
most significant bits of EOS, which are ones, and there must be fewer than eight
of them. Both come out of the same check: the state the decoder stops in has to
be one the table marked as acceptable to stop in, and the only such states are
the root and the first seven steps along the chain of ones leading away from it.

Output past a limit the caller sets. This is the one that matters most. Huffman
is a compression, so a small number of bytes on the wire can expand a long way,
and a decoder that grows a buffer until the input runs out is a decoder that can
be made to allocate far more than the peer sent. The caller passes the most it
is willing to receive and the decode stops the moment it would go past.
"""

from httpx._bytes import Bytes, _hex_digit
from httpx._exceptions import ErrorKind, new_error
from httpx._proto.h2._huffman_data import (
    HUFFMAN_ACCEPTED,
    HUFFMAN_CODE_WIDTH,
    HUFFMAN_CODES,
    HUFFMAN_FAIL,
    HUFFMAN_STATE_WIDTH,
    HUFFMAN_STATES,
    HUFFMAN_SYMBOL,
)


def _hex_at(table: StaticString, at: Int, width: Int) -> Int:
    var bytes = table.as_bytes()
    var value = 0
    for i in range(at, at + width):
        value = value * 16 + _hex_digit(bytes[i])
    return value


def _remote(message: String) -> Error:
    return new_error(ErrorKind.REMOTE_PROTOCOL_ERROR, message)


def huffman_encoded_length[o: ImmOrigin](data: Span[UInt8, o]) -> Int:
    """How many bytes `huffman_encode` would produce.

    Worth having on its own, because HPACK only sends a Huffman string when it
    is shorter than the literal, so the encoder has to know the length before it
    decides to spend anything on producing it.
    """
    var bits = 0
    for i in range(len(data)):
        var at = Int(data[i]) * HUFFMAN_CODE_WIDTH + 8
        bits += _hex_at(HUFFMAN_CODES, at, 2)
    return (bits + 7) // 8


def huffman_encode[o: ImmOrigin](data: Span[UInt8, o], mut out: Bytes):
    """Append the Huffman coding of `data` to `out`.

    The tail is padded to a byte boundary with ones, which is the prefix of the
    EOS code. That is what RFC 7541 section 5.2 asks for, and it is why a
    decoder can tell padding from a truncated code without being told how many
    bits were real.
    """
    var bits = UInt64(0)
    var held = 0

    for i in range(len(data)):
        var at = Int(data[i]) * HUFFMAN_CODE_WIDTH
        var code = UInt64(_hex_at(HUFFMAN_CODES, at, 8))
        var length = _hex_at(HUFFMAN_CODES, at + 8, 2)
        # The longest code is thirty bits and fewer than eight are ever held
        # over, so the accumulator never carries more than thirty seven.
        bits = (bits << UInt64(length)) | code
        held += length
        while held >= 8:
            held -= 8
            out.append(UInt8((bits >> UInt64(held)) & 0xFF))

    if held > 0:
        var pad = UInt64(8 - held)
        out.append(UInt8(((bits << pad) | ((UInt64(1) << pad) - 1)) & 0xFF))


def huffman_decode[
    o: ImmOrigin
](data: Span[UInt8, o], limit: Int) raises -> Bytes:
    """Decode `data`, refusing to produce more than `limit` bytes.

    `limit` is not a suggestion and there is no variant without one. The caller
    always knows what it is decoding into, whether that is a header name, a
    header value or an entry about to go into the dynamic table, and each of
    those has a size the peer already agreed to.
    """
    var out = Bytes()
    var state = 0
    # An empty string is a valid encoding of nothing, so the loop below starts
    # from a position it is allowed to stop in.
    var accepted = True

    for i in range(len(data)):
        var byte = Int(data[i])
        for shift in range(4, -1, -4):
            var nibble = (byte >> shift) & 0xF
            var at = (state * 16 + nibble) * HUFFMAN_STATE_WIDTH
            var flags = _hex_at(HUFFMAN_STATES, at + 2, 2)

            if flags & HUFFMAN_FAIL:
                raise _remote(
                    "the server sent a Huffman string containing the end of"
                    " string symbol"
                )

            if flags & HUFFMAN_SYMBOL:
                if len(out) >= limit:
                    raise _remote(
                        String(
                            (
                                "the server sent a Huffman string that decodes"
                                " to more than "
                            ),
                            limit,
                            " bytes",
                        )
                    )
                out.append(UInt8(_hex_at(HUFFMAN_STATES, at + 4, 2)))

            state = _hex_at(HUFFMAN_STATES, at, 2)
            accepted = (flags & HUFFMAN_ACCEPTED) != 0

    if not accepted:
        # Either the last code was cut off partway through, or the padding was
        # not ones, or there was a whole byte of it. All three mean the same
        # thing: these bytes are not what an encoder following the RFC produces.
        raise _remote("the server sent a Huffman string with invalid padding")

    return out^
