#!/usr/bin/env python3
"""The test runner.

Mojo 1.0 has no `mojo test` subcommand, only the assertions in `std.testing`,
so the project owns its runner. This script finds every `def test_*` under
tests/, generates a Mojo main that calls each one, compiles it and runs it.

The test files themselves are plain Mojo with no runner specific machinery in
them. When Mojo ships a native test runner this script is deleted and the tests
stay exactly as they are.

    pixi run test
    python tools/mojotest/run.py --filter cookie
    python tools/mojotest/run.py --fail-fast
    python tools/mojotest/run.py --repeat 20 --filter parser
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TESTS = ROOT / "tests"
GENERATED = TESTS / "_generated_main.mojo"

# A test is a top level `def test_*` that takes no arguments. Anything indented
# is a method or a nested helper and is not a test.
TEST_RE = re.compile(r"^def (test_[A-Za-z0-9_]*)\s*\(\s*\)", re.MULTILINE)


def mojo_binary() -> str:
    """Find a `mojo` that can also find its own standard library.

    Under `pixi run` the environment is already activated and plain `mojo`
    works. Run straight from a shell it usually is not, and the bare binary
    inside a pixi environment compiles nothing because it cannot locate `std`.
    The launcher pixi puts in `~/.pixi/bin` activates first, so fall back to
    that before giving up. Set MOJO to override.
    """
    override = os.environ.get("MOJO")
    if override:
        return override
    if os.environ.get("PIXI_PROJECT_ROOT") or os.environ.get("CONDA_PREFIX"):
        found = shutil.which("mojo")
        if found:
            return found
    launcher = Path.home() / ".pixi" / "bin" / "mojo"
    if launcher.exists():
        return str(launcher)
    found = shutil.which("mojo")
    if found:
        return found
    print(
        "mojo not found. Run `pixi run test`, or set MOJO to the binary.",
        file=sys.stderr,
    )
    sys.exit(2)


def discover(filter_: str | None) -> list[tuple[str, str, Path]]:
    """Return (module, function, path) for every test, sorted by module."""
    found: list[tuple[str, str, Path]] = []
    for path in sorted(TESTS.rglob("test_*.mojo")):
        module = ".".join(path.relative_to(ROOT).with_suffix("").parts)
        for name in TEST_RE.findall(path.read_text()):
            if filter_ and filter_ not in name and filter_ not in module:
                continue
            found.append((module, name, path))
    return found


def check_unique(tests: list[tuple[str, str, Path]]) -> None:
    """Test names have to be unique across the whole suite.

    The generated main imports every test into one namespace, so a duplicate
    name would silently shadow rather than run twice. Better to say so.
    """
    seen: dict[str, Path] = {}
    clashes = []
    for _, name, path in tests:
        if name in seen and seen[name] != path:
            clashes.append(f"  {name}\n    {seen[name]}\n    {path}")
        seen[name] = path
    if clashes:
        print("duplicate test names:", file=sys.stderr)
        print("\n".join(clashes), file=sys.stderr)
        print("\nTest names must be unique across the suite.", file=sys.stderr)
        sys.exit(2)


def generate(tests: list[tuple[str, str, Path]], repeat: int, fail_fast: bool) -> str:
    by_module: dict[str, list[str]] = {}
    for module, name, _ in tests:
        by_module.setdefault(module, []).append(name)

    lines = [
        "# Generated by tools/mojotest/run.py. Do not edit and do not commit.",
        "from std.time import perf_counter_ns",
        "",
    ]
    for module in sorted(by_module):
        names = ", ".join(sorted(by_module[module]))
        lines.append(f"from {module} import {names}")

    lines += [
        "",
        "",
        "def _run[name: StaticString](t: def () raises thin) -> Int:",
        "    var start = perf_counter_ns()",
        "    try:",
        "        t()",
        "    except e:",
        "        print('FAIL', name)",
        "        print('     ', String(e))",
        "        return 1",
        "    var micros = (perf_counter_ns() - start) // 1000",
        "    print('PASS', name, '(', micros, 'us )')",
        "    return 0",
        "",
        "",
        "def main() raises:",
        "    var failed = 0",
        "    var total = 0",
        f"    for _ in range({repeat}):",
    ]
    for _, name, _ in tests:
        lines.append("        total += 1")
        lines.append(f'        failed += _run["{name}"]({name})')
        if fail_fast:
            lines += [
                "        if failed != 0:",
                "            print('stopping after first failure')",
                "            raise Error('test run failed')",
            ]
    lines += [
        "    print('')",
        "    if failed != 0:",
        "        print(failed, 'of', total, 'failed')",
        "        raise Error('test run failed')",
        "    print(total, 'passed')",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Run the mojo.httpx test suite.")
    ap.add_argument("--filter", help="only tests whose name or module contains this")
    ap.add_argument("--fail-fast", action="store_true", help="stop at the first failure")
    ap.add_argument(
        "--repeat",
        type=int,
        default=1,
        metavar="N",
        help="run the suite N times, for shaking out flakes",
    )
    ap.add_argument(
        "--seed", type=int, help="seed for property tests, recorded in the output"
    )
    ap.add_argument("--keep", action="store_true", help="leave the generated main behind")
    args = ap.parse_args()

    tests = discover(args.filter)
    if not tests:
        where = f" matching {args.filter!r}" if args.filter else ""
        print(f"no tests found{where}", file=sys.stderr)
        return 1
    check_unique(tests)

    if args.seed is not None:
        print(f"seed {args.seed}")
    print(f"running {len(tests)} test(s)\n")

    GENERATED.write_text(generate(tests, args.repeat, args.fail_fast))
    try:
        cmd = [mojo_binary(), "run", "-I", str(ROOT), str(GENERATED)]
        if args.seed is not None:
            cmd += ["--", str(args.seed)]
        return subprocess.call(cmd, cwd=ROOT)
    finally:
        if not args.keep:
            GENERATED.unlink(missing_ok=True)


if __name__ == "__main__":
    sys.exit(main())
