"""Turn the vendored Public Suffix List into a Mojo table.

    python tools/gen_psl.py            rewrite httpx/_util/_psl_data.mojo
    python tools/gen_psl.py --check    fail if the file on disk is out of date

The table is embedded in the library rather than read from disk at runtime.
A client that needs a data file next to it to be correct is a client that is
silently insecure the first time somebody vendors it without the file, and the
cookie rule this list backs is a security control.

Three things happen on the way in. Comments and blank lines go, because the
lookup only ever asks whether an exact rule is present. Every non ASCII label
becomes its punycode A-label, because that is the form a cookie domain is
compared in and converting at lookup time would mean doing it on every request.
And the result is sorted by byte value, which is what lets the lookup binary
search a single blob with no offset table beside it.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "tests" / "data" / "LOCK.toml"
OUTPUT = ROOT / "httpx" / "_util" / "_psl_data.mojo"

# Wide enough that the generated file is readable in a diff, narrow enough that
# it stays inside the line length the formatter uses everywhere else.
CHUNK = 60


def source_path_and_digest() -> tuple[Path, str]:
    with LOCK.open("rb") as handle:
        locked = tomllib.load(handle)["file"]["public-suffix-list"]
    return ROOT / locked["path"], locked["sha256"]


def to_ascii(label: str) -> str:
    """One label in the form a hostname is compared in.

    A wildcard stays a wildcard. An ASCII label is lowercased, since the list is
    written in lower case but nothing enforces it. Anything else is punycode
    encoded directly rather than run through Python's `idna` codec, because that
    codec applies the IDNA2003 mapping and this file is already normalized; using
    it would mean the table was built by a different rule than the one
    `httpx/_util/idna.mojo` uses to build the names looked up in it.
    """
    if label == "*":
        return label
    if label.isascii():
        return label.lower()
    return "xn--" + label.encode("punycode").decode("ascii")


def rules_from(path: Path) -> list[str]:
    seen: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("//"):
            continue
        negated = line.startswith("!")
        body = line[1:] if negated else line
        rule = ".".join(to_ascii(label) for label in body.split("."))
        seen.add(("!" if negated else "") + rule)
    return sorted(seen)


def render(rules: list[str], digest: str) -> str:
    # One escaped newline is two characters in the source and splitting it across
    # two literals produces a file that does not parse, so the blob is chunked by
    # token rather than by character.
    tokens: list[str] = []
    for index, rule in enumerate(rules):
        if index:
            tokens.append("\\n")
        tokens.extend(rule)
    lines = [
        '"""The Public Suffix List, as one sorted blob.',
        "",
        "Generated by tools/gen_psl.py from the copy vendored under tests/data.",
        "Do not edit. Run `python tools/gen_psl.py` after refreshing the corpus.",
        "",
        "The rules are newline separated and sorted by byte value, so a lookup is",
        "a binary search that walks back to the nearest newline rather than an",
        "index of offsets sitting beside the data. That halves what has to be",
        "embedded and removes the one thing that can go out of sync with it.",
        '"""',
        "",
        # Wrapped here rather than on one line because a 64 character digest puts
        # that line over the limit and `mojo format` would rewrite it, which would
        # then read as the generated file being out of date on the next check.
        "comptime PSL_SOURCE_SHA256 = StaticString(",
        f'    "{digest}"',
        ")",
        "",
        f"comptime PSL_RULE_COUNT = {len(rules)}",
        "",
        "comptime PSL_RULES = StaticString(",
    ]
    chunk = ""
    for token in tokens:
        if len(chunk) + len(token) > CHUNK:
            lines.append(f'    "{chunk}"')
            chunk = ""
        chunk += token
    if chunk:
        lines.append(f'    "{chunk}"')
    lines.append(")")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the generated file matches the vendored list",
    )
    args = parser.parse_args()

    path, digest = source_path_and_digest()
    if not path.exists():
        print(
            f"{path.relative_to(ROOT)} is missing."
            " Run `python tools/vendor/fetch.py --update`.",
            file=sys.stderr,
        )
        return 1
    found = hashlib.sha256(path.read_bytes()).hexdigest()
    if found != digest:
        print(
            "the vendored list does not match the lock. Run"
            " `pixi run vendor-check` first.",
            file=sys.stderr,
        )
        return 1

    rules = rules_from(path)
    rendered = render(rules, digest)

    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != rendered:
            print(
                f"psl: {OUTPUT.relative_to(ROOT)} is out of date."
                " Run `python tools/gen_psl.py`.",
                file=sys.stderr,
            )
            return 1
        print(f"psl: ok, {len(rules)} rules match the vendored list")
        return 0

    OUTPUT.write_text(rendered)
    print(f"psl: wrote {len(rules)} rules to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
