"""Turn the vendored http-state cookie corpus into a Mojo fixture.

    pixi run python tools/gen_cookie_cases.py          rewrite the fixture
    pixi run python tools/gen_cookie_cases.py --check  fail if it is out of date

Run it through `pixi run`, because the output goes through `mojo format` and the
toolchain is only on PATH there.

The corpus is JSON and this library does not have a JSON reader yet, since the
`JSON` value type lands with the content layer. Rather than block a conformance
harness on that, the cases are compiled into Mojo source ahead of time. It turns
out to be the better shape anyway: the compiler checks the fixture, the escapes
are the language's own rather than a format invented for the occasion, and a
diff on the fixture shows exactly which cases changed when the corpus is
refreshed.

The corpus records what a browser does. Each case names a set of `Set-Cookie`
headers delivered to one URL and the exact `Cookie` header expected on a later
request to another. The URLs are not in the file because the whole suite uses
the same server, so they are reconstructed here the way the suite's own runner
does: cookies are set at `/cookie-parser?<id>` on `home.example.org` and read
back at `sent-to` if the case gives one, or `/cookie-parser-result?<id>` if not.

Cases whose name starts with `DISABLED_` are dropped, because the corpus itself
marks them as not describing agreed behaviour.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from mojogen import formatted, mojo_string

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "tests" / "data" / "LOCK.toml"
OUTPUT = ROOT / "tests" / "fixtures" / "cookie_cases.mojo"

BASE = "http://home.example.org"
SET_AT = "/cookie-parser?"
READ_AT = "/cookie-parser-result?"


def source_path_and_digest() -> tuple[Path, str]:
    with LOCK.open("rb") as handle:
        locked = tomllib.load(handle)["file"]["http-state-cookies"]
    return ROOT / locked["path"], locked["sha256"]


def cases_from(path: Path) -> list[dict[str, object]]:
    out: list[dict[str, object]] = []
    for case in json.loads(path.read_text(encoding="utf-8")):
        name = case["test"]
        if name.startswith("DISABLED_"):
            continue
        target = case.get("sent-to")
        if target is None:
            target = READ_AT + name.lower()
        expected = "; ".join(
            f"{sent['name']}={sent['value']}" for sent in case["sent"]
        )
        out.append(
            {
                "name": name,
                "url": BASE + SET_AT + name.lower(),
                "target": target,
                "received": case["received"],
                "expected": expected,
            }
        )
    return out


def render(cases: list[dict[str, object]], digest: str) -> str:
    lines = [
        '"""Cookie conformance cases, compiled from the vendored corpus.',
        "",
        "Generated by tools/gen_cookie_cases.py from tests/data/cookies/parser.json.",
        "Do not edit. Run `pixi run python tools/gen_cookie_cases.py` to redo it.",
        "",
        "Each case delivers `received` as Set-Cookie headers to `url`, then asks for",
        "the Cookie header a request to `target` would carry, and compares it against",
        "`expected`. An empty `expected` means no Cookie header at all.",
        '"""',
        "",
        "comptime COOKIE_CORPUS_SHA256 = StaticString(",
        f'    "{digest}"',
        ")",
        "",
        "",
        "struct CookieCase(Copyable, Movable):",
        "    var name: String",
        "    var url: String",
        "    var target: String",
        "    var received: List[String]",
        "    var expected: String",
        "",
        "    def __init__(",
        "        out self,",
        "        name: StringSpan,",
        "        url: StringSpan,",
        "        target: StringSpan,",
        "        var received: List[String],",
        "        expected: StringSpan,",
        "    ):",
        "        self.name = String(name)",
        "        self.url = String(url)",
        "        self.target = String(target)",
        "        self.received = received^",
        "        self.expected = String(expected)",
        "",
        "",
        "def cookie_cases() -> List[CookieCase]:",
        "    var out = List[CookieCase]()",
    ]
    for case in cases:
        received = ", ".join(mojo_string(header) for header in case["received"])
        lines.append("    out.append(")
        lines.append("        CookieCase(")
        lines.append(f"            {mojo_string(case['name'])},")
        lines.append(f"            {mojo_string(case['url'])},")
        lines.append(f"            {mojo_string(case['target'])},")
        lines.append(f"            [{received}],")
        lines.append(f"            {mojo_string(case['expected'])},")
        lines.append("        )")
        lines.append("    )")
    lines.append("    return out^")
    return formatted("\n".join(lines) + "\n", "cookie_cases.mojo")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the fixture matches the vendored corpus",
    )
    args = parser.parse_args()

    path, digest = source_path_and_digest()
    if not path.exists():
        print(
            f"{path.relative_to(ROOT)} is missing."
            " Run `python tools/vendor/fetch.py --update`.",
            file=sys.stderr,
        )
        return 1
    found = hashlib.sha256(path.read_bytes()).hexdigest()
    if found != digest:
        print(
            "the vendored corpus does not match the lock. Run"
            " `pixi run vendor-check` first.",
            file=sys.stderr,
        )
        return 1

    cases = cases_from(path)
    rendered = render(cases, digest)

    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != rendered:
            print(
                f"cookies: {OUTPUT.relative_to(ROOT)} is out of date."
                " Run `pixi run python tools/gen_cookie_cases.py`.",
                file=sys.stderr,
            )
            return 1
        print(f"cookies: ok, {len(cases)} cases match the vendored corpus")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    print(f"cookies: wrote {len(cases)} cases to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
